# Generated by Django 3.2.5 on 2021-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='valid_until',
            field=models.DateTimeField(null=True),
        ),
    ]
